name: check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v7

      - name: Setup pnpm and Node
        uses: pnpm/setup@v1
        with:
          runtime: node@26
          cache: true
          install: false

      - run: make setup
      - run: make lint
      - run: make test
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: make lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: make test
